#include "ansi.h"

#define ROSE_PINE_MAIN

#ifdef ROSE_PINE_MAIN
#	define ROSE_PINE__NC            ANSI_RGB(22, 20, 31)
#	define ROSE_PINE_BASE           ANSI_RGB(25, 23, 36)
#	define ROSE_PINE_SURFACE        ANSI_RGB(31, 29, 46)
#	define ROSE_PINE_OVERLAY        ANSI_RGB(38, 35, 58)
#	define ROSE_PINE_MUTED          ANSI_RGB(110, 106, 134)
#	define ROSE_PINE_SUBTLE         ANSI_RGB(144, 140, 170)
#	define ROSE_PINE_TEXT           ANSI_RGB(224, 222, 244)
#	define ROSE_PINE_LOVE           ANSI_RGB(235, 111, 146)
#	define ROSE_PINE_GOLD           ANSI_RGB(246, 193, 119)
#	define ROSE_PINE_ROSE           ANSI_RGB(235, 188, 186)
#	define ROSE_PINE_PINE           ANSI_RGB(49, 116, 143)
#	define ROSE_PINE_FOAM           ANSI_RGB(156, 207, 216)
#	define ROSE_PINE_IRIS           ANSI_RGB(196, 167, 231)
#	define ROSE_PINE_HIGHLIGHT_LOW  ANSI_RGB(33, 32, 46)
#	define ROSE_PINE_HIGHLIGHT_MED  ANSI_RGB(64, 61, 82)
#	define ROSE_PINE_HIGHLIGHT_HIGH ANSI_RGB(82, 79, 103)
#	define ROSE_PINE_NONE           ANSI_RESET
#endif

#define TBD        ANSI_MAGENTA
#define ROSE_PINE_ ANSI_MAGENTA

#define COLOR_PREPROC      ROSE_PINE_FOAM
#define COLOR_NOT_EQUAL    ROSE_PINE_SUBTLE
#define COLOR_DOUBLE_QUOTE ROSE_PINE_GOLD
#define COLOR_AMPERSAND    ROSE_PINE_SUBTLE
#define COLOR_SINGLE_QUOTE ROSE_PINE_GOLD
#define COLOR_LEFT_PAREN   ROSE_PINE_PINE
#define COLOR_RIGHT_PAREN  ROSE_PINE_PINE
#define COLOR_ASTERISK     ROSE_PINE_SUBTLE
#define COLOR_INCREMENT    ROSE_PINE_SUBTLE
#define COLOR_COMMA        ROSE_PINE_NONE
#define COLOR_DECREMENT    ROSE_PINE_SUBTLE
#define COLOR_COLON        ROSE_PINE_NONE
#define COLOR_SEMICOLON    ROSE_PINE_NONE
#define COLOR_EQUAL        ROSE_PINE_SUBTLE
#define COLOR_EQUAL_EQUAL  ROSE_PINE_SUBTLE
#define COLOR_GREATER      ROSE_PINE_SUBTLE
#define COLOR_LEFT_BRACE   ROSE_PINE_NONE
#define COLOR_RIGHT_BRACE  ROSE_PINE_NONE
#define COLOR_CHARACTER    ROSE_PINE_PINE
#define COLOR_CONST        ROSE_PINE_GOLD
#define COLOR_ELSE         ROSE_PINE_PINE
#define COLOR_ESCAPE_SEQ   ROSE_PINE_PINE
#define COLOR_GOTO         ROSE_PINE_PINE
#define COLOR_IDENTIFIER   ROSE_PINE_TEXT
#define COLOR_IF           ROSE_PINE_PINE
#define COLOR_NULL         ROSE_PINE_PINE
#define COLOR_NUMBER       ROSE_PINE_GOLD
#define COLOR_PRIMITIVE    ROSE_PINE_PINE
#define COLOR_RETURN       ROSE_PINE_PINE
#define COLOR_SIZEOF       ROSE_PINE_PINE
#define COLOR_STATEMENT    ANSI_BOLD ROSE_PINE_PINE
#define COLOR_STATIC       ROSE_PINE_GOLD
#define COLOR_STRING       ROSE_PINE_GOLD
#define COLOR_SYS_STRING   ROSE_PINE_GOLD
#define COLOR_TYPE         ROSE_PINE_FOAM
#define COLOR_WHILE        ROSE_PINE_PINE
