#ifndef TOKEN_TYPE_H
#define TOKEN_TYPE_H

typedef enum {
	TOKEN_TYPE_UNKNOWN = 0,
	TOKEN_TYPE_PREPROC,
	TOKEN_TYPE_SYS_LIB_STRING,
	TOKEN_TYPE_STRING,
	TOKEN_TYPE_KEYWORD,
	TOKEN_TYPE_PRIMITIVE,
	TOKEN_TYPE_COMMENT,
	TOKEN_TYPE_OPERATOR,
	TOKEN_TYPE_IDENTIFIER,
	TOKEN_TYPE_DELIMITER,
	TOKEN_TYPE_PUNCTUATION,
	TOKEN_TYPE_NUMBER_LITERAL,
	TOKEN_TYPE_TYPE_IDENTIFIER,
	TOKEN_TYPE_ESCAPE_SEQUENCE,
	TOKEN_TYPE_FIELD_IDENTIFIER,
	TOKEN_TYPE_CHARACTER,
	TOKEN_TYPE_STATEMENT_IDENTIFIER,
} TokenType;

TokenType token_type_from_str(const char *str);

#endif
